image: alpine/old
packages:
  - findutils
  - linux-headers
  - libffi-dev
  - libressl-dev
  - python3
  - python3-dev
  - py3-pip
  - py3-requests
# Enable this to debug
# shell: true
secrets:
  - 262ecd1a-0945-48f7-920f-367c59e107bc
  - 0e73e604-2a62-48ae-b5b6-9b6b0e09fc4d
  - ea368a24-78eb-4f2c-bca2-52a791042348
sources:
   - hg+ssh://hg@hg.sr.ht/~ocurero/sqlalchemy-querybuilder
tasks:
  - sync_github: |
      cd sqlalchemy-querybuilder
      sudo pip3 -q install hg-git
      sudo pip3 -q install dulwich
      echo "[extensions]" >>./.hg/hgrc
      echo "hgext.bookmarks =" >>./.hg/hgrc
      echo "hggit = " >>./.hg/hgrc
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      hg bookmark -r default master # so a ref gets created
      hg push git+ssh://git@github.com/ocurero/sqlalchemy-querybuilder.git || hg push git+ssh://git@github.com/ocurero/sqlalchemy-querybuilder.git | grep "no changes found"
  - clone_github: |
      rm -R sqlalchemy-querybuilder && git clone git@github.com:ocurero/sqlalchemy-querybuilder.git
  - pass_tests: |
      cd sqlalchemy-querybuilder
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
      source $HOME/.poetry/env
      poetry install --quiet
      poetry run tox
  - update_readthedocs: |
      curl -X POST -d @/home/build/RTD_TOKEN https://readthedocs.org/api/v2/webhook/sqlalchemy-querybuilder/139469/
  - upload_codecov: |
      cd sqlalchemy-querybuilder && sudo pip3 -q install coverage
      curl -s https://codecov.io/bash | bash -s -- -Z -t @/home/build/CODECOV_TOKEN
triggers: null
