image: alpine/3.9
packages:
  - findutils
  - linux-headers
  - libffi-dev
  - libressl-dev
  - python3
  - python3-dev
# For hg-git  
  - python
  - python-dev
  - py2-pip
# Enable this to debug
# shell: true
secrets:
  - 262ecd1a-0945-48f7-920f-367c59e107bc
  - 0e73e604-2a62-48ae-b5b6-9b6b0e09fc4d
sources:
   - hg+ssh://hg@hg.sr.ht/~ocurero/sqlalchemy-querybuilder
tasks:
  - sync_github: |
      cd sqlalchemy-querybuilder
      sudo pip -q install hg-git
      echo "[extensions]" >>./.hg/hgrc
      echo "hgext.bookmarks =" >>./.hg/hgrc
      echo "hggit = " >>./.hg/hgrc
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      hg bookmark -r default master # so a ref gets created
      hg push git+ssh://git@github.com/ocurero/sqlalchemy-querybuilder.git || hg push git+ssh://git@github.com/ocurero/sqlalchemy-querybuilder.git | grep "no changes found"
  - clone_github: |
      rm -R sqlalchemy-querybuilder && git clone git@github.com:ocurero/sqlalchemy-querybuilder.git
  - mkvenv: 'python3 -m venv CI'
  - tests: 'source CI/bin/activate

    cd sqlalchemy-querybuilder

    pip install --quiet --upgrade pip coverage

    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
    | python

    source $HOME/.poetry/env

    poetry -q update

    poetry -q install

    poetry run coverage run --source=sqlalchemy-querybuilder/ -m pytest

    if [ $? -eq 0 ]; then curl -s https://codecov.io/bash | bash -s -- -Z -t @/home/build/CODECOV_TOKEN;
    fi'
triggers: null
